language: android
android:
  components:
    # The SDK version used to compile your project
    - android-19

    # The BuildTools version used by your project
    - tools
    - build-tools-23.0.2
    
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    - sys-img-x86-android-19
    
# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-19 --abi x86
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
