language: android
env:
  global:
    - compileSdkVersion=19
    - targetSdkVersion=19
    - toolsVersion=23.0.2
    - ANDROID_ABI=armeabi-v7a
android:
  components:
    # The SDK version used to compile your project
    - android-${compileSdkVersion}

    # The BuildTools version used by your project
    - tools
    - build-tools-${toolsVersion}
    
    # if you need to run emulator(s) during your tests
    # - sys-img-armeabi-v7a-android-19
    - sys-img-${ANDROID_ABI}-android-${targetSdkVersion}
    
# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-${targetSdkVersion} --abi ${ANDROID_ABI}
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
